In [5]:
import numpy as np

original_list =  [12.23, 13.32, 100, 36.32]

arr = np.array(original_list)
arr


array([ 12.23,  13.32, 100.  ,  36.32])

In [7]:
np.random.randint(2,10,size=(3,3))

array([[5, 6, 6],
       [3, 3, 8],
       [4, 7, 6]], dtype=int32)

In [13]:
array = np.zeros(11)
array[6] = 11
array


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [16]:
np.random.randint(12,38,10)

array([27, 33, 20, 17, 26, 12, 26, 35, 37, 31], dtype=int32)

In [24]:
original_array = np.array([1, 2, 3, 4])

arr1 = np.array(original_array, dtype=float)


In [27]:
import numpy as np

celsius = np.array([
    [0, 12, 45.21, 34, 99.91],
    [-17.78, -11.11, 7.34, 1.11, 37.73]
])

fahrenheit = (celsius * 9/5) + 32

print("Celsius array:\n", celsius)
print("\nFahrenheit array:\n", fahrenheit)

Celsius array:
 [[  0.    12.    45.21  34.    99.91]
 [-17.78 -11.11   7.34   1.11  37.73]]

Fahrenheit array:
 [[ 3.20000e+01  5.36000e+01  1.13378e+02  9.32000e+01  2.11838e+02]
 [-4.00000e-03  1.20020e+01  4.52120e+01  3.39980e+01  9.99140e+01]]


In [34]:
import numpy as np

original_values = np.array([10, 20, 30])

extended_values = np.append(original_values, [40, 50, 60, 70, 80, 90])

print("Original_Values:",original_values)
print("Extended_Values:",extended_values)

Original_Values: [10 20 30]
Extended_Values: [10 20 30 40 50 60 70 80 90]


In [44]:
original_array = np.random.randint(0,10,10)

mean = np.mean(original_array)
median = np.median(original_array)
standard_deviation = np.std(original_array)


print("Array:", original_array)
print("Mean:", mean)
print("Median:",median)
print("Standard_Deviation:",standard_deviation)


Array: [5 9 5 6 2 6 0 7 2 5]
Mean: 4.7
Median: 5.0
Standard_Deviation: 2.5317977802344327


In [51]:
import numpy as np
arrays = np.random.randint(0,100, size =(10,10))
arrays

max_value = np.max(arrays)
min_value = np.min(arrays)

print("Max_value:",max_value)
print("Min_Value:",min_value)

Max_value: 99
Min_Value: 0


In [53]:
import numpy as np

random_array = np.random.randint(10,1000, size =(3,3,3))

random_array

array([[[ 33, 603, 525],
        [298, 719, 631],
        [911, 323, 196]],

       [[384,  76, 675],
        [903, 932, 451],
        [624, 905, 662]],

       [[ 12, 600, 513],
        [555, 824, 348],
        [398, 764, 369]]], dtype=int32)